### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by WuTianming** [jinshulumengchuang/sfpkg#7]
I found this in file 'sfroot': 我在sfroot文件里找到这个：
bash "/mnt/sfpkg/"$file"/**root.sh**" "/mnt/sfpkg/"$file""
but did you make a typo? 但是，是不是你打错了？
It should be **auto.sh** instead of **root.sh** 应该是auto.sh而不是root.sh

**Comment by losywee** [comment]
应用程序文件目录内包含  auto.sh，然后执行 mksfpkg 程序目录

**Comment by WuTianming** [comment]
@Iosywee
我是说，文件里好像把auto.sh打成了root.sh

**Comment by losywee** [comment]
嗯嗯，知道你的意思
